### ISSUE TITLE
有个wsl的问题想请教一下

### ISSUE THREAD

**Issue by Jekinnnnnn** [abtswath/v2ex-topic-viewer#1]
不好意思，我在主页上没找到你的邮箱，只能开个不相关的issue。
我留意到你提了下面这个issue：https://github.com/microsoft/WSL/issues/11318
我现在也有一样的问题，但是我尝试了在.wslconfig中[wsl2]下配置了hv_utils.timesync_implicit=0，没有起作用。
不知道你当时是怎么解决这个问题的，现在还能用吗？
我的是Debian
WSL 版本： 2.3.26.0
内核版本： 5.15.167.4-1
WSLg 版本： 1.0.65
MSRDC 版本： 1.2.5620
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.26100.1-240331-1435.ge-release
Windows 版本： 10.0.22631.4460

**Comment by abtswath** [comment]
刚试了下，我是可以生效的

我的 WSL 版本：
WSL 版本： 2.3.26.0
内核版本： 5.15.167.4-1
WSLg 版本： 1.0.65
MSRDC 版本： 1.2.5620
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.26100.1-240331-1435.ge-release
Windows 版本： 10.0.22631.4460

你可以 `cat /proc/cmdline` 检查下启动参数中是否包含 `hv_utils.timesync_implicit=0`
```sh
root@abtswath:~# cat /proc/cmdline
initrd=\initrd.img WSL_ROOT_INIT=1 panic=-1 nr_cpus=20 hv_utils.timesync_implicit=1 console=hvc0 debug pty.legacy_count=0 WSL_ENABLE_CRASH_DUMP=1 hv_utils.timesync_implicit=0
```
或者排查下是不是有 `ntp` 或 `systemd-timesyncd` 服务同步了时间

**Comment by Jekinnnnnn** [comment]
我的是
```
initrd=\initrd.img WSL_ROOT_INIT=1 panic=-1 nr_cpus=2 hv_utils.timesync_implicit=1 cgroup_no_v1=all console=hvc0 debug pty.legacy_count=0 WSL_ENABLE_CRASH_DUMP=1
```
我的是这样的，我看你有两个hv_utils.timesync_implicit，而我只有1个，那个应该是默认参数，难道是我wslconfig配置的问题？
贴一下我的config
```
[wsl2]
processors=2
memory=4GB
swap=8GB
networkingMode=mirrored
swapFile=D:\\server\\WslSwap.vhdx
firewall=false
vmIdleTimeout=-1
hv_utils.timesync_implicit=0
```

**Comment by abtswath** [comment]
内核启动参数是写在 `kernelCommandLine` 配置里的

[https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config#main-wsl-settings](https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config#main-wsl-settings)

**Comment by abtswath** [comment]
> 内核启动参数是写在 `kernelCommandLine` 配置里的
> 
> https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config#main-wsl-settings

[wsl2]
kernelCommandLine="hv_utils.timesync_implicit=0"

**Comment by Jekinnnnnn** [comment]
可以了感谢。
